### ISSUE TITLE
Format of index tarball seems to differ from what the script expects

### ISSUE THREAD

**Issue by chrislf** [AleXoundOS/haskell-stack-mirror-script#7]
To get the script to extract the filenames from 01-index.tar.gz, I needed to modify the grep and sed regexes slightly: I'm not sure if this is because of a change in the index tarball format?
```diff
@@ -210,8 +210,8 @@ echo "======= producing list of packages urls to download ====================="
 HACKAGE_MIRROR_ESC=$(echo $HACKAGE_MIRROR | sed -e 's/[\/&]/\\&/g')
 
 tar --list -f "$MIRROR_DIR/$(basename $HACKAGE_INDEX)" \
-  | egrep "(.*)/([[:digit:].]+)/$" \
-  | sed "s/\(.*\)\/\(.*\)\/$/$HACKAGE_MIRROR_ESC\/\1-\2.tar.gz/" \
+  | egrep "(.*)/([[:digit:].]+)/" \
+  | sed "s/\(.*\)\/\(.*\)\/.*$/$HACKAGE_MIRROR_ESC\/\1-\2.tar.gz/" \
   | sort -o download-packages-urls
 if [ $? -ne 0 ]; then
     echo "error getting list of packages urls to download"
```

**Comment by AleXoundOS** [comment]
Probably something has changed in the naming scheme. Thank you for the report, I will check it in the nearest 2-3 days.

**Comment by AleXoundOS** [comment]
Sorry for such a long unexpected delay.
I could not reproduce the problem. Can you try again with the latest master (4e71487cf5ed1f4a6ac9f6e91c457de6261a50e5)? And if the problem persists provide some logs to get a better understanding of what's going wrong.

**Comment by chrislf** [comment]
I couldn't reproduce it at home. I strongly suspect firewall shenanigans in the corporate network. Either way, looks like the problem is not with your script. Apologies for the noise.
